#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formularios_DB_simple
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CursoLinQ")]
	public partial class EmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertALUMNO(ALUMNO instance);
    partial void UpdateALUMNO(ALUMNO instance);
    partial void DeleteALUMNO(ALUMNO instance);
    #endregion
		
		public EmpresaDataContext() : 
				base(global::Formularios_DB_simple.Properties.Settings.Default.CursoLinQConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public EmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<ALUMNO> ALUMNO
		{
			get
			{
				return this.GetTable<ALUMNO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado
	{
		
		private string _codigo;
		
		private string _nombre;
		
		private string _apellidoPaterno;
		
		private string _apellidoMaterno;
		
		private System.Nullable<int> _edad;
		
		public Empleado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaterno", DbType="VarChar(50)")]
		public string apellidoPaterno
		{
			get
			{
				return this._apellidoPaterno;
			}
			set
			{
				if ((this._apellidoPaterno != value))
				{
					this._apellidoPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaterno", DbType="VarChar(50)")]
		public string apellidoMaterno
		{
			get
			{
				return this._apellidoMaterno;
			}
			set
			{
				if ((this._apellidoMaterno != value))
				{
					this._apellidoMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int")]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this._edad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ALUMNO")]
	public partial class ALUMNO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDALUMNO;
		
		private string _NOMBREALUMNO;
		
		private string _APELLIDOPATERNOALUMNO;
		
		private string _APELLIDOMATERNOALUMNO;
		
		private System.Nullable<int> _NOTA1;
		
		private System.Nullable<int> _NOTA2;
		
		private System.Nullable<int> _NOTA3;
		
		private System.Nullable<int> _NOTA4;
		
		private string _CURSOFAVORITO;
		
		private string _NIVELACADEMICO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDALUMNOChanging(int value);
    partial void OnIDALUMNOChanged();
    partial void OnNOMBREALUMNOChanging(string value);
    partial void OnNOMBREALUMNOChanged();
    partial void OnAPELLIDOPATERNOALUMNOChanging(string value);
    partial void OnAPELLIDOPATERNOALUMNOChanged();
    partial void OnAPELLIDOMATERNOALUMNOChanging(string value);
    partial void OnAPELLIDOMATERNOALUMNOChanged();
    partial void OnNOTA1Changing(System.Nullable<int> value);
    partial void OnNOTA1Changed();
    partial void OnNOTA2Changing(System.Nullable<int> value);
    partial void OnNOTA2Changed();
    partial void OnNOTA3Changing(System.Nullable<int> value);
    partial void OnNOTA3Changed();
    partial void OnNOTA4Changing(System.Nullable<int> value);
    partial void OnNOTA4Changed();
    partial void OnCURSOFAVORITOChanging(string value);
    partial void OnCURSOFAVORITOChanged();
    partial void OnNIVELACADEMICOChanging(string value);
    partial void OnNIVELACADEMICOChanged();
    #endregion
		
		public ALUMNO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDALUMNO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDALUMNO
		{
			get
			{
				return this._IDALUMNO;
			}
			set
			{
				if ((this._IDALUMNO != value))
				{
					this.OnIDALUMNOChanging(value);
					this.SendPropertyChanging();
					this._IDALUMNO = value;
					this.SendPropertyChanged("IDALUMNO");
					this.OnIDALUMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBREALUMNO", DbType="VarChar(50)")]
		public string NOMBREALUMNO
		{
			get
			{
				return this._NOMBREALUMNO;
			}
			set
			{
				if ((this._NOMBREALUMNO != value))
				{
					this.OnNOMBREALUMNOChanging(value);
					this.SendPropertyChanging();
					this._NOMBREALUMNO = value;
					this.SendPropertyChanged("NOMBREALUMNO");
					this.OnNOMBREALUMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOPATERNOALUMNO", DbType="VarChar(100)")]
		public string APELLIDOPATERNOALUMNO
		{
			get
			{
				return this._APELLIDOPATERNOALUMNO;
			}
			set
			{
				if ((this._APELLIDOPATERNOALUMNO != value))
				{
					this.OnAPELLIDOPATERNOALUMNOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDOPATERNOALUMNO = value;
					this.SendPropertyChanged("APELLIDOPATERNOALUMNO");
					this.OnAPELLIDOPATERNOALUMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOMATERNOALUMNO", DbType="VarChar(100)")]
		public string APELLIDOMATERNOALUMNO
		{
			get
			{
				return this._APELLIDOMATERNOALUMNO;
			}
			set
			{
				if ((this._APELLIDOMATERNOALUMNO != value))
				{
					this.OnAPELLIDOMATERNOALUMNOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDOMATERNOALUMNO = value;
					this.SendPropertyChanged("APELLIDOMATERNOALUMNO");
					this.OnAPELLIDOMATERNOALUMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTA1", DbType="Int")]
		public System.Nullable<int> NOTA1
		{
			get
			{
				return this._NOTA1;
			}
			set
			{
				if ((this._NOTA1 != value))
				{
					this.OnNOTA1Changing(value);
					this.SendPropertyChanging();
					this._NOTA1 = value;
					this.SendPropertyChanged("NOTA1");
					this.OnNOTA1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTA2", DbType="Int")]
		public System.Nullable<int> NOTA2
		{
			get
			{
				return this._NOTA2;
			}
			set
			{
				if ((this._NOTA2 != value))
				{
					this.OnNOTA2Changing(value);
					this.SendPropertyChanging();
					this._NOTA2 = value;
					this.SendPropertyChanged("NOTA2");
					this.OnNOTA2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTA3", DbType="Int")]
		public System.Nullable<int> NOTA3
		{
			get
			{
				return this._NOTA3;
			}
			set
			{
				if ((this._NOTA3 != value))
				{
					this.OnNOTA3Changing(value);
					this.SendPropertyChanging();
					this._NOTA3 = value;
					this.SendPropertyChanged("NOTA3");
					this.OnNOTA3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTA4", DbType="Int")]
		public System.Nullable<int> NOTA4
		{
			get
			{
				return this._NOTA4;
			}
			set
			{
				if ((this._NOTA4 != value))
				{
					this.OnNOTA4Changing(value);
					this.SendPropertyChanging();
					this._NOTA4 = value;
					this.SendPropertyChanged("NOTA4");
					this.OnNOTA4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURSOFAVORITO", DbType="VarChar(100)")]
		public string CURSOFAVORITO
		{
			get
			{
				return this._CURSOFAVORITO;
			}
			set
			{
				if ((this._CURSOFAVORITO != value))
				{
					this.OnCURSOFAVORITOChanging(value);
					this.SendPropertyChanging();
					this._CURSOFAVORITO = value;
					this.SendPropertyChanged("CURSOFAVORITO");
					this.OnCURSOFAVORITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVELACADEMICO", DbType="VarChar(100)")]
		public string NIVELACADEMICO
		{
			get
			{
				return this._NIVELACADEMICO;
			}
			set
			{
				if ((this._NIVELACADEMICO != value))
				{
					this.OnNIVELACADEMICOChanging(value);
					this.SendPropertyChanging();
					this._NIVELACADEMICO = value;
					this.SendPropertyChanged("NIVELACADEMICO");
					this.OnNIVELACADEMICOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
